apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort          # expose on host
  selector:
    app: python-app       # must match deployment labels
  ports:
    - port: 80            # service port
      targetPort: 80      # container port
      nodePort: 30007     # host port
